### ISSUE TITLE
Project Server Actions

### ISSUE THREAD

**Issue by Oba-One** [greenpill-dev-guild/impact-reef#31]
**External Attestations**
Project attestation
Acknowledgment

**Queries**

- Fetch all projects
  - Fetch project attestations
  - Fetch project acknowledgment

**Internal Attestations**
Metrics
- Points to project
Metric Acknowledgment
Metric Unacknowledgment

Metrics can be revocable

**Libraries/Tools**
IPFS
EAS

Local Storage Draft Metrics
Review before publish

**Comment by bitbeckers** [comment]
These are the schemas currently known, so #44 incorporates those:

```
project: https://optimism.easscan.org/schema/view/0x0e5d439a46d50507c63ea277b75c4d87711cc9d1754103393066927ee9be9fe3

project metadata snapshot: https://optimism.easscan.org/schema/view/0x9a384502b07bb8dfe65a784d0abee1dc22ff541024a9965d78ef7934dda7b6ca
-> data will be available via API, lmk if you want me to help you access

RPGF application: https://optimism.easscan.org/schema/view/0x5a2187bc9d5f9a35b18538f30614ea92fc31c7f704707161de395f2ce6c09cab
```

**Comment by bitbeckers** [comment]
We can't really complete is, because it looks like we'll be trailing changes made by OP for the upcoming rounds. In other words, what we know now are project owner's Farcaster ID, their Farcaster profile data and the project metadata stored for the application. 

I like that we're not dependant on an OP API but EAS as a whole and would prefer to keep it like that. So maybe for now this issue is done?

**Comment by Oba-One** [comment]
From my understanding this ticket is to do the EAS work of building a server action that fetches the attestations for projects and then their metadata from IPFS and creates an list to send to the client of different projects.

**Comment by Oba-One** [comment]
> @Oba-One we can't really complete this, because it looks like we'll be trailing changes made by OP for the upcoming rounds. In other words, what we know now are project owner's Farcaster ID, their Farcaster profile data and the project metadata stored for the application.
> 
> I like that we're not dependant on an OP API but EAS as a whole and would prefer to keep it like that. So maybe for now this issue is done?

From my understanding this ticket is to do the EAS work of building a server action that fetches the attestations for projects and then their metadata from IPFS and creates an list to send to the client of different projects.

**Comment by Oba-One** [comment]
From my understanding this ticket is to do the EAS work of building a server action that fetches the attestations for projects and then their metadata from IPFS and creates an list to send to the client of different projects. Based on the PR looks like that has been done,  so yea this is done.

@bitbeckers
