### ISSUE TITLE
Evaluation Attestation Schemas

### ISSUE THREAD

**Issue by Oba-One** [greenpill-dev-guild/impact-reef#33]
# Done State

- Evaluation schema deployed to EAS on Optimism Sepolia
  - Metric ID: String
  - Project ID: String 
  - Flagged Metrics: string[]
  - Tags: string[]
  - Stars: Number

# Technical Requirements

- Attestations can be revoked

# Resources

- [EAS](url)
- [Metric Garden](url)

**Comment by bitbeckers** [comment]
Changed this schema a little bit to the following schema:

```json
  {
    "name": "Project evaluation",
    "description": "Rate a project based on a set of metrics",
    "values": [
      {
        "type": "bytes32",
        "name": "projectUID"
      },
      {
        "type": "bytes32[]",
        "name": "metricUIDs"
      },
      {
        "type": "string",
        "name": "description"
      },
      {
        "type": "uint8",
        "name": "stars"
      }
    ],
    "parsed": "bytes32 projectUID, bytes32[] metricUIDs, string description, uint8 stars",
    "UID": "0xe623eafcf84d0a4d721f9531be103e5123cc61b60179b8577cca08316785d2c1"
  },
```

The reason for this, is that the requirement looked like we want a user to collect a bunch of metric, or attestations, and based on that relate a `star` score. It might need some tweaks, but I thik this schema definition could be improved.
